### ISSUE TITLE
NPE with lemminx

### ISSUE THREAD

**Issue by arysin** [eclipse/lemminx#1654] opened 2024-07-25 15:13 UTC
I've implemented lemminx plugin that provides a content assist for my xml files. It worked properly in Eclipse until 2024.06.
With Eclipse 2024.06 I am getting this message:
`[2024-07-25T11:10:06.542824969-04:00] LANGUAGE_SERVER_TO_LSP4E org.eclipse.wildwebdeveloper.xml:
{"jsonrpc":"2.0","id":"15","error":{"code":-32603,"message":"Internal error.","data":"java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke \"java.util.List.forEach(java.util.function.Consumer)\" because the return value of \"java.util.Map.get(Object)\" is null\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)\n\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)\nCaused by: java.lang.NullPointerException: Cannot invoke \"java.util.List.forEach(java.util.function.Consumer)\" because the return value of \"java.util.Map.get(Object)\" is null\n\tat org.eclipse.lemminx.utils.CompletionItemDefaultsUtils.setToMostCommonEditRange(CompletionItemDefaultsUtils.java:76)\n\tat org.eclipse.lemminx.utils.CompletionItemDefaultsUtils.process(CompletionItemDefaultsUtils.java:46)\n\tat org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:293)\n\tat org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:171)\n\tat org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$3(XMLTextDocumentService.java:264)\n\tat org.eclipse.lemminx.commons.ModelTextDocuments.lambda$computeModelAsync$0(ModelTextDocuments.java:118)\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)\n\t... 6 more\n"}}
`
From what I can tell the was a null check added to potentially handle this situation in org.eclipse.lemminx 0.27.1 but from what I can tell all current org.eclipse.m2e.editor.lemminx plugins (up to snapshot version) include org.eclipse.lemminx 0.27.0

**Comment by angelozerr** [comment] 2024-07-25 18:10
I think it is the dame issue than https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1628

**Comment by arysin** [comment] 2024-07-25 19:44
Thanks, yes, that's looks the same

**Comment by fbricon** [comment] 2024-07-25 19:50
Closing as duplicate of #1653

**Closed by fbricon** 2024-07-25 19:50 UTC
