### ISSUE TITLE
web-app in xml

### ISSUE THREAD

**Issue by vishalkumar57** [eclipse/lemminx#1157] opened 2022-01-27 07:34 UTC
There is '1' error in 'javaee_7.xsd'.

**Comment by fbricon** [comment] 2022-01-27 08:00
Can you provide a sample xml document reproducing the error?

**Comment by angelozerr** [comment] 2022-01-28 18:31
I suspect its when you are using wwd. If it that perhaps you have not the last version of wwd becàuse there were à fix at https://github.com/eclipse/wildwebdeveloper/pull/726

**Comment by angelozerr** [comment] 2022-01-31 12:57
I close this issue because I suppose it's the same than https://stackoverflow.com/questions/67271527/eclipse-language-servers-there-is-1-error-in-javaee-7-xsd (LemMinx integrated in WWD in Eclipse IDE).

With  vscode-xml we have not this problem. 

eclipse/wildwebdeveloper#726 has been merged,so please wait for a new release of WWD, and I hope it should fix this issue.

**Closed by angelozerr** 2022-01-31 12:57 UTC
