### ISSUE TITLE
Exception, when downloading certain schemes

### ISSUE THREAD

**Issue by deathaxe** [eclipse/lemminx#909] opened 2020-10-12 19:04 UTC
Opening a file called _delete-element.xsl_ with following content

<details>

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    xmlns:xr="http://www.oxygenxml.com/ns/xmlRefactoring"
    version="3.0"
    xmlns:saxon="http://saxon.sf.net/"
    xpath-default-namespace="http://www.oxygenxml.com/ns/samples/personal">
            
    <!-- The XPath identyfing the elements to be deleted -->        
    <xsl:param name="element_xpath" as="xs:string" required="yes"/>
    
    <!-- Identify the elements to be deleted -->
    <xsl:variable name="elements" as="element()*">
        <xsl:evaluate xpath="$element_xpath" as="element()*" context-item="/"/>
    </xsl:variable>
    
    <xsl:template match="*">
        <!-- Copy only those elements that were not matched by the '$element_xpath' XPath expression -->
        <xsl:variable name="intersection" select=". intersect $elements"/>
        <xsl:choose>
            <xsl:when test="empty($intersection)">
                <xsl:copy>
                    <xsl:apply-templates select="@*"/>
                    <xsl:apply-templates select="node()"/>
                </xsl:copy>
            </xsl:when>
        </xsl:choose>        
    </xsl:template>
    
    <xsl:template match="text() | comment() | processing-instruction() | @*">
        <xsl:copy>
            <xsl:apply-templates select="node() | @*"/>
        </xsl:copy>
    </xsl:template>
    
</xsl:stylesheet>
```

</details>

causes the following exception incase of cold cache (nothing downloaded yet, cache folder empty).

<details>

```
lemminx: Okt 12, 2020 08:54:01 java.util.logging.LogManager$RootLogger log()
Message: Log file could not be created, path not provided
lemminx: Okt 12, 2020 08:54:01 org.eclipse.lemminx.utils.FilesUtils saveToFile()
Message: The associated file system '~\lemminx\cache\https\www.w3.org\TR\xslt-30\schema-for-xslt30.xsd' + does not support the PosixFileAttributeView
java.lang.UnsupportedOperationException
	at java.nio.file.Files.setPosixFilePermissions(Unknown Source)
	at org.eclipse.lemminx.utils.FilesUtils.saveToFile(FilesUtils.java:155)
	at org.eclipse.lemminx.utils.FilesUtils.saveToFile(FilesUtils.java:135)
	at org.eclipse.lemminx.uriresolver.CacheResourcesManager.getResourceCachePath(CacheResourcesManager.java:207)
	at org.eclipse.lemminx.extensions.xsl.XSLURIResolverExtension.resolve(XSLURIResolverExtension.java:69)
	at org.eclipse.lemminx.uriresolver.URIResolverExtensionManager.resolve(URIResolverExtensionManager.java:93)
	at org.eclipse.lemminx.dom.DOMDocument.intializeExternalGrammar(DOMDocument.java:440)
	at org.eclipse.lemminx.dom.DOMDocument.initializeReferencedExternalGrammarIfNeeded(DOMDocument.java:409)
	at org.eclipse.lemminx.dom.DOMDocument.hasExternalGrammar(DOMDocument.java:396)
	at org.eclipse.lemminx.dom.DOMDocument.hasGrammar(DOMDocument.java:165)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.doDiagnostics(XMLValidator.java:75)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.ContentModelDiagnosticsParticipant.doDiagnostics(ContentModelDiagnosticsParticipant.java:48)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:85)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:53)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:159)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:168)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:466)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:459)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

lemminx: Okt 12, 2020 08:54:01 org.eclipse.lemminx.utils.FilesUtils saveToFile()
Message: The associated file system '~\lemminx\cache\https\www.w3.org\2001\xml.xsd' + does not support the PosixFileAttributeView
java.lang.UnsupportedOperationException
	at java.nio.file.Files.setPosixFilePermissions(Unknown Source)
	at org.eclipse.lemminx.utils.FilesUtils.saveToFile(FilesUtils.java:155)
	at org.eclipse.lemminx.utils.FilesUtils.saveToFile(FilesUtils.java:135)
	at org.eclipse.lemminx.uriresolver.CacheResourcesManager.getResourceCachePath(CacheResourcesManager.java:207)
	at org.eclipse.lemminx.extensions.xsd.XSDURIResolverExtension.resolve(XSDURIResolverExtension.java:70)
	at org.eclipse.lemminx.extensions.xsd.XSDURIResolverExtension.resolveEntity(XSDURIResolverExtension.java:84)
	at org.eclipse.lemminx.uriresolver.URIResolverExtensionManager.resolveEntity(URIResolverExtensionManager.java:105)
	at org.apache.xerces.impl.XMLEntityManager.resolveEntity(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.resolveDocument(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.resolveSchema(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.constructTrees(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.findSchemaGrammar(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
	at org.eclipse.lemminx.extensions.xerces.xmlmodel.XMLModelHandler.startElement(XMLModelHandler.java:196)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.parseXML(XMLValidator.java:108)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.doDiagnostics(XMLValidator.java:94)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.ContentModelDiagnosticsParticipant.doDiagnostics(ContentModelDiagnosticsParticipant.java:48)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:85)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:53)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:159)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:168)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:466)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:459)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

</details>

**Info**

- LemMinX 0.13.1
- Java jre1.8.0_251
- Windows 10 x64 2004

**Comment by angelozerr** [comment] 2020-10-13 06:12
It's the same issue than https://github.com/eclipse/lemminx/issues/734 

I notice that you try to write XSL 3.0 which is not supported by LemMinx (I mean validation) because the XSD Schema for XSL 3.0 is written in XSD 1.1 which is not supported by LemMinx.

**Comment by deathaxe** [comment] 2020-10-13 15:33
The provided file is part of a framework I was skimming over, but thanks for notifying about the limitations.

That said, this issue seems to be just a duplicate and may be closed as such.

**Comment by angelozerr** [comment] 2020-10-13 16:25
Duplicate of #734

**Closed by angelozerr** 2020-10-13 16:25 UTC
Labels: bug, duplicate
