### ISSUE TITLE
shutdown should unregister plugins

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#610] opened 2020-02-25 12:21 UTC
Shutting down the language server should unregister plugins so they could properly dispose their locks or other things.
Currently, those cannot be properly disposed from the plugin so the plugin needs to keep some static cache to avoid issues.

**Comment by mickaelistria** [comment] 2020-02-25 12:22
@AObuchow This is the reason why we cannot currently run proper unit tests for remote Maven repos in Maven plugin: the index contexts are not closed between tests.

**Comment by angelozerr** [comment] 2020-02-25 13:56
@mickaelistria https://github.com/angelozerr/lsp4xml/commit/8b086afc86c35477b73d80d17987781ae1de1b35 fixed this issue, no?

**Comment by AObuchow** [comment] 2020-02-25 15:12
> @mickaelistria [8b086af](https://github.com/angelozerr/lsp4xml/commit/8b086afc86c35477b73d80d17987781ae1de1b35) fixed this issue, no?

Yes this fixed it, I think this issue can be closed.

**Comment by angelozerr** [comment] 2020-03-09 07:30
Duplicate of https://github.com/eclipse/lemminx/issues/605

**Closed by angelozerr** 2020-03-09 07:30 UTC
Labels: duplicate
