### ISSUE TITLE
Auto-Change Closing Tag

### ISSUE THREAD

**Issue by BalduinLandolt** [eclipse/lemminx#817] opened 2020-07-05 09:22 UTC
Another feature that would be cool to have: When changing an opening tag, it should automatically change the closing tag with it.

**Comment by angelozerr** [comment] 2020-07-05 18:52
We have a PR for this great feature https://github.com/redhat-developer/vscode-xml/pull/213

**Comment by angelozerr** [comment] 2020-07-05 19:03
Duplicate of https://github.com/redhat-developer/vscode-xml/issues/130

**Closed by angelozerr** 2020-07-05 19:03 UTC
