### ISSUE TITLE
Type highlight all instead of by instance

### ISSUE THREAD

**Issue by AlexXuChen** [eclipse/lemminx#1050] opened 2021-06-04 13:47 UTC
Given this XSD file:
```xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://example.org/my-example"
    xmlns:NS="http://example.org/my-example">
    <xs:element name="foo" type="NS:bar"/>
    <xs:element name="barbar" type="NS:bar"/>
    <xs:element name="barbarbar" type="NS:bar"/>
    <!-- This comment contains bar-->
    <xs:complexType name="bar"></xs:complexType>
</xs:schema
```

I see the following behaviour when using highlighting when highlighting the name of a defined type:
![Peek 2021-06-03 14-56](https://user-images.githubusercontent.com/26389510/120807542-10fe8480-c516-11eb-9533-7859c6582d14.gif)

I believe the desired behaviour should be only the `NS:bar` in the `type` attribute of the `element` tag should be highlighted, whereas the current behaviour I see is highlighting all text occurrences of the `type`.

**Comment by angelozerr** [comment] 2021-06-04 14:29
It works for me (on Windows)

![image](https://user-images.githubusercontent.com/1932211/120817412-f9dd8800-c551-11eb-863b-4c29afef9224.png)

@datho7561 have you the same problem?

**Comment by datho7561** [comment] 2021-06-04 14:33
No, actually. I can't seem to reproduce. I'll look through my settings to see if I have something disabled.

**Comment by AlexXuChen** [comment] 2021-06-04 14:38
I do recall seeing it work on Angelo's side, which is why I was a bit confused why it didnt work for me. I can also confirm my vscode-xml is enabled.

**Comment by datho7561** [comment] 2021-06-04 14:41
If place the cursor somewhere on the `bar` definition without selecting it, then it will give Angelo's result. If you select `bar`, then it will give Alex's result.

**Comment by AlexXuChen** [comment] 2021-06-04 14:44
Ah, David is right, clicking once vs double clicking yields different results.

**Comment by AlexXuChen** [comment] 2021-06-04 14:47
![Peek 2021-06-04 10-45](https://user-images.githubusercontent.com/26389510/120820084-385b4e80-c522-11eb-9da8-c90cf9763b0d.gif)

**Comment by angelozerr** [comment] 2021-06-04 16:39
Good catch @datho7561 !

There is the same behavior with vscode-java extension (and other extensions too):

![VSCodeJavaHighighPb](https://user-images.githubusercontent.com/1932211/120834879-e6d3b380-c563-11eb-8000-5c5e84f6f1c9.gif)

So I think it's the behavior of vscode. I close this issue and mark as invalid.

**Closed by angelozerr** 2021-06-04 16:39 UTC
