### ISSUE TITLE
Error while downloading ... to ... with HTTPS

### ISSUE THREAD

**Issue by zewa666** [eclipse/lemminx#419] opened 2019-06-07 11:42 UTC
Hey there,

I've tried the VSCode extension today on a testng project in order to check out the DTD support. When I open the file `testng.xml`, which does point inside the DOCTYPE to a valid DTD endpoint, I do get the error:

`Error while downloading 'http://testng.org/testng-1.0.dtd' to /Users/MYUSERNAME/.lsp4xml/cache/http/testng.org/testng-1.0.dtd.
`

Now in this [related issue](https://github.com/cbeust/testng/issues/1385#issuecomment-480170577) there is a mention that an upgrade for HTTP -> HTTPS has been setup so I wonder whether this is the root cause.

Alternatively I'd like to know if there are any means to get more logs or info about the specific issue.

Here's the testng.xml file content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Tests" verbose="5">
  <test name="Test1">
    <packages>
      <package name="uitest.*"/>
    </packages>
  </test>
</suite>
```

**Comment by angelozerr** [comment] 2019-06-07 12:34
I can reproduce it and I have the following :

`SEVERE: Error while downloading http://testng.org/testng-1.0.dtd to C:\Users\azerr\.lsp4xml\cache\http\testng.org\testng-1.0.dtd : [sun.security.provider.certpath.SunCertPathBuilderException] unable to find valid certification path to requested target`

So as you said, it's a problem with HTTPS. A fix for that I think is to disable https when we try to download a resources.

@fbricon what do you think about that?

**Comment by zewa666** [comment] 2019-06-07 12:37
@angelozerr the error sounds pretty much like what the older version of TestNG is writing out. A recent fix seems to have [worked around](https://github.com/cbeust/testng/pull/2023) that. Is that maybe of help?

**Comment by angelozerr** [comment] 2019-06-07 14:23
I have tried quickly to ignore SSL by using code `HttpsTrustManager` from https://stackoverflow.com/questions/33084855/way-to-ignore-ssl-certificate-using-httpsurlconnection and it works now, but I'm not sure it's a recommended solution to ignore SSL.

@fbricon have you some suggestion?

**Comment by zewa666** [comment] 2019-06-07 17:36
This sounds a bit weird as it kinda defeats the purpose of ssl by allowing every selfsigned cert, potentially also malicious ones. But indeed it could be a great dev-feature to quickly try out things

Would there be a way to provide, via settings, a whitelist of trusted certs?

**Comment by fbricon** [comment] 2019-06-07 19:10
blindly accepting all self-signed certificates sounds like a bad idea, even if enabled via a preference.
I'm kinda OK with adding a whitelist of trusted certs, as that'd limit the surface area of potential XXE attacks, but I'd mark that preference as provisional, susceptible to be removed without a deprecating phase. Now the question is: how do you identify a certificate as a string? (i.e what do you add as a preference value?)

**Comment by zewa666** [comment] 2019-06-07 20:05
I'm actually not fully understanding from where the issue itself stems. Is it related to the SSL certificate used by testng.org and the url `http://testng.org/testng-1.0.dtd`? Looking at it nothing seems wrong. So what is this exception, mentioned above by @angelozerr, really telling us? Why would I have to install the certificate in my local keystore?

@fbricon as for whitelisting, one could store the paths to a container (pem, key, csr, whatever). My Java knowledge is very limited so I don't really know what it would take besides that to configure a self-signed cert with HttpsTrustManager.

**Comment by fbricon** [comment] 2019-06-07 20:08
the problem is the SSL Cert used by testng.org is unknown to the JDK. It should be fixable by installing the certificate manually https://docs.oracle.com/javase/tutorial/security/toolsign/rstep2.html

**Comment by zewa666** [comment] 2019-06-07 20:41
Yeah installing it manually is actually what I would have liked to bypass ;)
Maybe @cbeust can help us out here?

**Comment by zewa666** [comment] 2019-06-07 20:50
@fbricon as for self signed certs, would passing a custom truststore when starting up the lsp help? `-Djavax.net.ssl.trustStore=/app/security/truststore.jks`

**Comment by fbricon** [comment] 2019-06-07 20:52
I think it should work

**Comment by cbeust** [comment] 2019-06-08 01:39
I renewed the SSL certificate a couple of weeks ago, maybe there's some caching issue on your end?

As far as I can tell, the new certificate is valid.

**Comment by zewa666** [comment] 2019-06-11 10:28
@cbeust visiting https://testng.org in firefox (incognito mode) I do get the risk error report "SEC_ERROR_UNKNOWN_ISSUER", indicating that the certifacte issuer hasn't been recognized. So maybe all of that clears up why issues are happening

```
https://testng.org/

Der Certificate-Issuer der Gegenstelle wurde nicht erkannt.

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false

Zertifikatskette:

-----BEGIN CERTIFICATE-----
MIIGaDCCBVCgAwIBAgIQBcZ/YqM9KJShFqn8tVnr6jANBgkqhkiG9w0BAQsFADCB
jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
MB4XDTE5MDUyNjAwMDAwMFoXDTIwMDgyMzIzNTk1OVowTjEhMB8GA1UECxMYRG9t
YWluIENvbnRyb2wgVmFsaWRhdGVkMRQwEgYDVQQLEwtQb3NpdGl2ZVNTTDETMBEG
A1UEAxMKdGVzdG5nLm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AMO19SOvsf6svPNYERxo6B37xIP+540VVRfFiyPgAh6mObjJYEO8LhYbHXL5LQ8+
WCFb0Hr7lJoOUkuwYZGi79daHvEzJcrEy4kTSRI5A4CUlStg1E/fYSO0KKf91urQ
BOgDNMPNSAlb+Juz8PNQIvX7O/yS9H0TfNmKhj747IO7oB0x564v08OU4kFlbyJQ
PBOz4XdttQUJkMPZI4vHwzx1HfcHM7IjAElNh3/C/DWV/9ypZKM0HjNPjWQCyBaG
Pjan6z5UwGnbOmQreQgAGw0ms1PGYlIPLAemZcc+QqJgUoiKB1ymcOW9AeMRr1Ny
K8415tMfsTscBw+aluHUdiUCAwEAAaOCAv4wggL6MB8GA1UdIwQYMBaAFI2MXsRU
rYrhd+mb+ZsF4bgBjWHhMB0GA1UdDgQWBBSXdRP6pW3ftnr8k4HV9qaI/NrhmjAO
BgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcD
AQYIKwYBBQUHAwIwSQYDVR0gBEIwQDA0BgsrBgEEAbIxAQICBzAlMCMGCCsGAQUF
BwIBFhdodHRwczovL3NlY3RpZ28uY29tL0NQUzAIBgZngQwBAgEwgYQGCCsGAQUF
BwEBBHgwdjBPBggrBgEFBQcwAoZDaHR0cDovL2NydC5zZWN0aWdvLmNvbS9TZWN0
aWdvUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNydDAjBggrBgEF
BQcwAYYXaHR0cDovL29jc3Auc2VjdGlnby5jb20wJQYDVR0RBB4wHIIKdGVzdG5n
Lm9yZ4IOd3d3LnRlc3RuZy5vcmcwggGABgorBgEEAdZ5AgQCBIIBcASCAWwBagB3
ALvZ37wfinG1k5Qjl6qSe0c4V5UKq1LoGpCWZDaOHtGFAAABavN/L9UAAAQDAEgw
RgIhAOGjgNBraPvPj3ndxArIyrtS6vH3tfzNlvPMXU0mWpxpAiEA8wg7IGShT0GW
ixU5btqraB5+0Gu1bxD8jxj+/LBHWq8AdwBep3P531bA57U2SH3QSeAyepGaDISh
EhKEGHWWgXFFWAAAAWrzfzENAAAEAwBIMEYCIQCSUAKqh+wyThu+SXSum3BsGgI9
Xw7CmSFoQQ55cauAxgIhAP6uNljlbzkpWung0/bdWCLgXPeiKVi7X6NjHcwVSYbo
AHYAb1N2rDHwMRnYmQCkURX/dxUcEdkCwQApBo2yCJo32RMAAAFq838w6wAABAMA
RzBFAiAuoyIQbrMAJDOcKO7+MJCpEZr+zBe40E1G40W/W9HjfAIhAKNspJ+rVX6Y
324alvKkDbRVEYOFNKAa0sxMfac/OHtXMA0GCSqGSIb3DQEBCwUAA4IBAQCC4jJ5
gEriLw3pI0/HRRg+Ud4YCjrK6NyU45zEJr3/6SMpTcI88zRAim8/DhVkhi/iNx2R
dm6vZPGdt+a42LGhJGlBMLSRS3O+tXh++RytJmmkf3qRKMjdhBNSHvSOByEtNBSQ
bUONnlZtFcOEei6v+oaOrefa+HnHYigIGUEGRJmNnsy/6aHD70BQJ17PUfa1EVSF
r0Szp5nZMXopw4TN6KDuA6Ub9ToiwgsH+XprlW75SaRCfUL1TzmBg9IfJXxXB4z1
wu0s3LSjUtyTB3Zr2S5H9Jcs77c56NCJrfPf5LVEsLCQzvktb/fsKlBTb3bXu+Ow
zBLvY6p7GgufNsqG
-----END CERTIFICATE-----

```

**Comment by cbeust** [comment] 2019-06-11 13:41
It looks like Comodo recently changed its name to Sectigo and the name change and root cert haven't propagated everywhere yet. Are you using Ubuntu by any chance?

**Comment by zewa666** [comment] 2019-06-11 15:35
Happens both on Ubuntu and Mac. Colleague replicated it on win as well.

**Comment by snjeza** [comment] 2019-06-11 15:35
@cbeust To test your server configuration, you can try the following:
```
openssl s_client -connect testng.org:443
```
or
https://whatsmychaincert.com/?testng.org

**Comment by zewa666** [comment] 2019-06-11 16:36
@fbricon and @angelozerr I'm sorry that we're hijacking this issue for the testng case. Btw how did you guys get the exception message? I was looking around in vscode and couldnt find anything in the output window.

**Comment by angelozerr** [comment] 2019-06-11 17:31
You must enable logs with vscode settings.json

`"xml.logs.client": true`

and after you should see:

```
[Error - 19:30:05] Jun 11, 2019 07:30:05 org.eclipse.lsp4xml.uriresolver.CacheResourcesManager lambda$downloadResource$0()
Message: Error while downloading http://testng.org/testng-1.0.dtd to C:\Users\azerr\.lsp4xml\cache\http\testng.org\testng-1.0.dtd : [sun.security.provider.certpath.SunCertPathBuilderException] unable to find valid certification path to requested target
```

**Comment by angelozerr** [comment] 2019-06-11 18:35
@zewa666 if you wish to have completion and validation for testng you could download at hand with browser the testng dtd and copy paste in Users/MYUSERNAME/.lsp4xml/cache/http/testng.org/testng-1.0.dtd.

It's an hack by waiting for fixing this hard issue i think

**Comment by zewa666** [comment] 2019-06-11 20:23
Funny you mention that, thats what I already tried ;) its not that easy for my specific case though. Im working on a Test focused IDE called [Webtestit](https://ranorex.com/webtestit) where we scaffold a Java project, based on TestNG for the client. Messing with their local cache is certainly just a last resort I'd like to do. While at it let me say huge thanks to all of you for both the fantastic xml and java ls.

**Comment by cbeust** [comment] 2019-06-12 07:00
@snjeza 

I ran ` openssl s_client -connect testng.org:443` and after a lengthy output, I get:

```
    Start Time: 1560322701
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```

**Comment by snjeza** [comment] 2019-06-12 16:12
@cbeust Take a look at the following line to see what the issue is:
```
$ openssl s_client -connect testng.org:443
...
verify error:num=20:unable to get local issuer certificate
...
```
You need to set your certificate chain correctly.
I suppose you have used the following command:
```
cat testng.org.crt testng_org.ca-bundle > ssl-bundle.crt
```
and your testng.org.crt doesn't have the newline at the end.
ssl-bundle.crt contains the following line:
```
...
-----END CERTIFICATE----------BEGIN CERTIFICATE-----
...
```
You can edit the file as follows:
```
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
```
or create the file using the following command:
```
cat testng.org.crt >ssl-bundle.crt; echo -e "\n" >>ssl-bundle.crt; cat testng_org.ca-bundle >>ssl-bundle.crt
```

See an example of the correctly configured site - https://whatsmychaincert.com/?openshift.com

**Comment by snjeza** [comment] 2020-01-28 19:47
Now, https://testng.com is set properly. I can't reproduce the issue anymore.

**Comment by fbricon** [comment] 2020-05-13 14:48
This is has been fixed upstream. Closing.

**Closed by fbricon** 2020-05-13 14:48 UTC

**Comment by ChetanKSA** [comment] 2023-11-18 17:08
https://testng.org/testng-1.0.dtd

I tried removing "s" from "https" and error disappeared. Not sure if  it's the right solution and it works for all.
