### ISSUE TITLE
Lemminx fails to initialize

### ISSUE THREAD

**Issue by enxio** [eclipse/lemminx#969] opened 2021-01-20 12:16 UTC
Using the latest version (4e58859d7af1b17032e3aaa3b554ddb9fcbf9730), I get the following error on initialization time.

I am not sure if this is related to #964.

```
[2021-01-20 13:09:23.124] [exthost] [error] Activating extension redhat.vscode-xml failed due to an error:
[2021-01-20 13:09:23.338] [exthost] [error] Error: Internal error.
    at /Users/.../.vscode/extensions/redhat.vscode-xml-0.14.0/node_modules/vscode-jsonrpc/lib/main.js:438:57
    at undefined (/Users/.../.vscode/extensions/redhat.vscode-xml-0.14.0/node_modules/vscode-jsonrpc/lib/main.js:507:26)
    at Immediate.<anonymous> (/Users/.../.vscode/extensions/redhat.vscode-xml-0.14.0/node_modules/vscode-jsonrpc/lib/main.js:232:35)
    at processImmediate (internal/timers.js:439:21)
```

Please let me know what information would be needed to further track this down. Thanks.

**Comment by angelozerr** [comment] 2021-01-21 08:28
@enxio I don't understand your trace is about 0.14.0 (which is released) although the current version of vscode-xml should be 0.15.0?

I think the problem is related to #964

**Comment by enxio** [comment] 2021-01-21 09:01
@angelozerr due to #594, I am tracking the latest changes in lemminx in enxio/lsp4xml and try it out with the vscode-xml I have (which is the one that's released). 

Thanks for the confirmation though.

**Comment by angelozerr** [comment] 2021-01-21 09:13
> @angelozerr due to #594,

Wow it should be awful for you -( I try to work on this issue but it's not a trivial issue and I find the Oxygen formatting looks strange in some context.

I close this issue since it's a duplicate of #964

**Closed by angelozerr** 2021-01-21 09:13 UTC
