### ISSUE TITLE
validation claims error in jakartaee_9.xsd

### ISSUE THREAD

**Issue by chris21k** [eclipse/lemminx#1042] opened 2021-05-20 06:57 UTC
The Eclipse IDE maintainers asked me to post an xml validation issue for JEE 9 here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=572027

Thanks for looking into it,
Chris

**Comment by fbricon** [comment] 2021-05-20 07:23
can you paste the content of ~/.lemminx/cache/https/jakarta.ee/xml/ns/jakartaee/jakartaee_9.xsd?

**Comment by angelozerr** [comment] 2021-05-20 12:12
@chris21k could you give open the faces-config.xml withgeneric editor and check you have this outline:

![image](https://user-images.githubusercontent.com/1932211/118976504-5e56ef80-b975-11eb-999d-04e24413ace8.png)

**Comment by chris21k** [comment] 2021-05-30 10:11
Added ".txt" suffix so that gihub gets a supported externsion: [jakartaee_9.xsd.txt](https://github.com/eclipse/lemminx/files/6566014/jakartaee_9.xsd.txt)

After planing the cursor in eclipse within in the value (within quotes) of attribute xmlns Imy otuline window does not display anything. However I have [web-facesconfig_3_0.xsd.txt](https://github.com/eclipse/lemminx/files/6566021/web-facesconfig_3_0.xsd.txt) in the same directory as jakartaee_9.xsd and as you have.

**Comment by angelozerr** [comment] 2021-05-31 08:00
Sorry I forget to mention taht you should install https://github.com/eclipse/wildwebdeveloper

**Comment by angelozerr** [comment] 2021-05-31 08:09
> Sometimes JEE artifacts like web.xml oder faces-config.xml show validation errors "There is '1' error in 'jakartaee_9.xsd'". The error is visualized on the line of the outermost tag after the xml-header by a red error cross. I can perfectly reproduce that by importing a war file as project. However, it also shows up from time to time on other actions. Saving the file without any real changes (i.e. inserting a whitespace -> undo -> save) eliminates the display of the error.
Is there realy a flaw in the xsd file? Maybe/probably this is more likely an bug?

If I understand correctly, when you import your WAR, you have this error. I have the impression that in this usecase, some dependency XSD (like jakartaee_web_services_client_2_0.xsd) are not downloaded yet and jakartaee_9.xsd has an error.

Could you check you have  jakartaee_web_services_client_2_0.xsd in the same folder jakartaee_9.xsd from lemminx cache, please.

![image](https://user-images.githubusercontent.com/1932211/120161985-375faf80-c1f8-11eb-84d4-8f25e5faf563.png)

If you have those files, have you again the same problem when you import a new WAR?

**Comment by chris21k** [comment] 2021-06-03 10:45
Here the current conten of my cache:
![cache](https://user-images.githubusercontent.com/30565861/120631168-d9d19a00-c467-11eb-84a3-81e7ce92168e.png)

Same problem when importing a new war-File. This does not depend on the presence of jakartaee_web_services_client_2_0.xml in the cache. Sometimes the similar error is also marked in web.xml. If I insert a whitespace in either of web.xml or faces-config.xml the error goes away from BOTH files. However, some times later it comes back at least in faces-config.xml . Also it comes back when newly import a war file.
If in jakartaee-9.xsd should be an error, where is it? Why then eclipse suppresses the error (at least for some tme) as descriped above?

WildWebDeveloper 0.10.6 is installed. After I unapcked eclipse 4.19 sdk I installes wtp from the std repo 2021-03 - http://download.eclipse.org/releases/2021-03 WTP by ticking everythin under   Web, XML, Java EE and OSGi Enterprise Development except php and rap tools. This also includes wildwebdeveloper .

**Comment by chris21k** [comment] 2021-06-03 10:52
If this is easier for you, we can do a skype or zoom meeting where I can show a live demonstration and we can tryout some things. Just give me some coordinates.

**Comment by chris21k** [comment] 2021-06-04 05:56
As told, making a change to the web.xml or faces-config.xml, undoying the change and save elimitates the errors. Then I close the edior of the file. A simple reopening of the file in the internal editor shows the error again.

**Comment by angelozerr** [comment] 2021-06-04 07:27
> If this is easier for you, we can do a skype or zoom meeting where I can show a live demonstration and we can tryout some things. Just give me some coordinates.

Thanks for your help. Have a gmail account to do a google meeting?

> As told, making a change to the web.xml or faces-config.xml, undoying the change and save elimitates the errors. Then I close the edior of the file. A simple reopening of the file in the internal editor shows the error again.

Could you close all editors and open the jakarta file which causes problem. Have you an error in this case?

**Comment by chris21k** [comment] 2021-06-04 09:15
> open the jakarta file which causes problem. Have you an error in this case?
Yes, I already tried to describe that.

> Have a gmail account to do a google meeting?
Yes lets do that. I have now startet a meeting where you can join me:
meet.google.com/byd-pvxk-vco
PIN: 785 758 136#

**Comment by chris21k** [comment] 2021-06-04 13:50
@angelozerr: Ok, we probably should specify a fix time slot, for example Mo June 7th 8-9 CET, Mo 16-17, Tue 9:30-10 8th, Tue 13:30-14, or Sat 8-9 5th. Or feel free to suggest a slot which is suitable for you. I think we only need a couple of minutes.
Thanks,
Chris

**Comment by chris21k** [comment] 2021-06-11 09:06
Eclipse 4.20 alias 2021-06 RC does contain the same bug.

**Comment by angelozerr** [comment] 2021-06-11 10:54
@chris21k I sent you an email last week (that I peek from eclipse bugzilla) but I suppose it's the wron email, please write me an email in order to we discuss together. Hope you will have a gmail on order to we could chat together.

**Comment by angelozerr** [comment] 2021-06-11 18:56
Ok I can reproduce the issue with a fresh Eclipse IDE (the last). I can explain the problem but I don't know how to fix it (for the moment).

When you have `"There is '1' error in 'jakartaee_9.xsd'"` error, you must open the XSD file (from the cache) and you should see 1 error and 1 warning:

![image](https://user-images.githubusercontent.com/1932211/121735087-eef89980-caf5-11eb-9c98-479c1365c24f.png)

There is a warning:

```
schema_reference.4: Failed to read schema document 'platform:/plugin/org.eclipse.xsd/cache/www.w3.org/2001/xml.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.	jakartaee_9.xsd	/lemminx-cache/https/jakarta.ee/xml/ns/jakartaee	line 52	Language Servers


```
![image](https://user-images.githubusercontent.com/1932211/121735143-05065a00-caf6-11eb-85d1-22e3b9386fb4.png) 

which try to define xml:lang attribute inside xml.xsd file. But here the xml.xsd cannot be retrieved (the warning message) and you have the error:

![image](https://user-images.githubusercontent.com/1932211/121736077-5ebb5400-caf7-11eb-873f-f890b9847a1e.png)

It tries to download the XSD from `platform:/plugin/org.eclipse.xsd/cache/www.w3.org/2001/xml.xsd` but platform is specific to Eclipse IDE. In other words when `http://www.w3.org/2001/xml.xsd` must be resolved, it says that `platform:/plugin/org.eclipse.xsd/cache/www.w3.org/2001/xml.xsd`  is the location of XSD. I don't know who do that?

I have the impression than LemMinx is configured to use XML catalog from WTP:

![image](https://user-images.githubusercontent.com/1932211/121735783-eeacce00-caf6-11eb-9105-523428ea9826.png)

@mickaelistria have you some idea?

**Comment by angelozerr** [comment] 2021-06-11 18:59
@chris21k please note that you can disable LemMinx validation:

![image](https://user-images.githubusercontent.com/1932211/121736447-dee1b980-caf7-11eb-8da4-a0fb9fc6ed7b.png)

**Comment by chris21k** [comment] 2021-06-12 16:10
@angelozerr I did send you an E-Mail to the address you provided in GitHub profile.

**Comment by angelozerr** [comment] 2021-06-13 10:10
Ok after debugging i found the problem. When xml language server is started it build a xml catalog from wtp catalog  contribution extension point. It doesnt take care of platform uri. I will try to create a pr to fix it.

**Comment by angelozerr** [comment] 2021-07-01 10:43
I close this issue since problem comes from WWD. I created a PR to fix this issue in https://github.com/eclipse/wildwebdeveloper/pull/682

**Closed by angelozerr** 2021-07-01 10:43 UTC
